baseurl: https://ku-sldg.github.io/copland/
markdown: kramdown
title: Copland
subtitle: Semantics, languages and tools for layered attestation
github: https://github.com/ku-sldg/copland
description: The objective of the Copland project is formally specifing and building tools for remote attestation.  The core Copland language definition provides a formally verified definition of attestation protocols.  Based on the core language, researchers are developing tools for remote attestation including attestation managers, exchange formats, and attestation service providers.
sponsors: The National Security Agency Science of Security Lablet Program, DARPA Cyber-Aware Systems Engineering, Kansas City National Security Campus, Air Force Research Laboratory, and Ripple University Blockchain Research Initiative

